### ISSUE TITLE
 Generating Presigned URLs

### ISSUE THREAD

**Issue by wwj718** [minio/cookbook#106]
hi 
Can I use boto3 to  generating presigned URL?  I can not find the document

**Comment by koolhead17** [comment]
@wwj718 Any specific reason you are not using [minio-py](https://github.com/minio/minio-py)  client library, we have examples documented [here](https://github.com/minio/minio-py/tree/master/examples) and it works for both AWS S3 and Minio, like (presigned_get_object.py)[https://github.com/minio/minio-py/blob/master/examples/presigned_get_object.py]

For generating presigned URL for boto3, following this [document](http://boto3.readthedocs.io/en/latest/guide/s3.html#generating-presigned-urls) it can be achieved.

 Replace the credentials with your local setup.

```
 
import boto3
from botocore.client import Config
import requests

# Get the service client.

s3 = boto3.client('s3',
                    endpoint_url='http://localhost:9000',
                    aws_access_key_id='BKIKJAA5BMMU2RHO6IBB ',
                    aws_secret_access_key='V8f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12',
                    config=Config(signature_version='s3v4'),
                    region_name='us-east-1')



# Generate the URL to get 'key-name' from 'bucket-name'
url = s3.generate_presigned_url(
    ClientMethod='get_object',
    Params={
        'Bucket': 'atul',
        'Key': 'eReceipt.pdf'
    }
)

# Use the URL to perform the GET operation. You can use any method you like
# to send the GET, but we will use requests here to keep things simple.
response = requests.get(url)
print url
```
You can ``curl`` the url it prints, hope it helps.

**Comment by wwj718** [comment]
@koolhead17 Got it！ Thanks a lot

**Comment by wwj718** [comment]
Hi @koolhead17 

When I  upload  a file to generate_presigned_url with brower ,the uploaded file contains a WebKitFormBoundary header and footer, like this:

```
------WebKitFormBoundarySL7tAOmBXV8JjBpj^M
Content-Disposition: form-data; name="test.txt"; filename="test.txt"^M
Content-Type: text/plain^M
^M
```

How to get rid of WebKitFormBoundary in uploaded file

Thanks

**Comment by harshavardhana** [comment]
Fixed the referenced document, closing.

**Comment by wwj718** [comment]
@koolhead17  Got it , thanks !

**Comment by BrunoBA** [comment]
> Fixed the referenced document, closing.

Can you tell me what you did for this upload to work? I spending a lot of time to fix tho solve this... ):

**Comment by strongpapazola** [comment]
> Hello @wwj718 I see a solution for the same suggested on [stackoverflow](http://stackoverflow.com/questions/38781909/webkitformboundary-included-in-file-payload-on-direct-upload-to-s3) See if you can apply it with your code and it helps.
> 
> thanks.

remember for change your upload types
like

```
const file = $input[0].files[0];
 ```
![image](https://github.com/minio/docs/assets/48545591/51192db2-712a-4e1a-a6fe-858dda225934)
