### ISSUE TITLE
Verify if mountain duck on OS X supports http profile

### ISSUE THREAD

**Issue by koolhead17** [minio/cookbook#113]
We need to install mountain duck on a fresh mac machine & test/verify if it requires the http profile.

**Comment by koolhead17** [comment]
I will need help from anyone with OS X to test this for me. cc: @deekoder

**Comment by koolhead17** [comment]
This can be closed via https://github.com/minio/cookbook/pull/126

**Comment by harshavardhana** [comment]
Github issue should close after the aforementioned patch is merged - reference this github issue there.

**Comment by koolhead17** [comment]
closing this. PR is merged.
