### ISSUE TITLE
docs: test and document the steps for running jfrog artifactory OSS edition

### ISSUE THREAD

**Issue by harshavardhana** [minio/cookbook#136]
https://www.jfrog.com/  -- JFrog provides world-class infrastructure for software management and distribution

Ideally we should get the blog here on their official website. 

https://www.jfrog.com/knowledge-base/how-to-configure-openstack-swift-s3-provider-with-artifactory/

**Comment by GarimaKapoor** [comment]
We should ask the community member who was using the artifactory to write the post. If he can tell us his use case we can help him do the post.

**Comment by harshavardhana** [comment]
> We should ask the community member who was using the artifactory to write the post. If he can tell us his use case we can help him do the post.

:+1:

**Comment by harshavardhana** [comment]
Setting priority high as unknown priority // cc @deekoder

**Comment by deekoder** [comment]
We dont plan to address this unless community is really really wanting this. Please indicate by reopening if needed.
