### ISSUE TITLE
Add Minio as storage backend for  GITLAB

### ISSUE THREAD

**Issue by koolhead17** [minio/cookbook#149]
Our community member [dcharbonnier] suggested below mentioned configuration to use Minio as object storage backend for gitlab.

```
environment:
     GITLAB_OMNIBUS_CONFIG: |
       registry_external_url 'https://registry.xxx.org'
       external_url 'https://gitlab.xxx.org'
       gitlab_rails['gitlab_ssh_host'] = 'gitlab.xxx.org'
       gitlab_rails['registry_enabled'] = true
       gitlab_rails['registry_host'] = "https://registry.xxx.org"
       gitlab_rails['registry_api_url'] = "http://localhost:5000"
       gitlab_rails['registry_port'] = "443"
       registry['enable'] = true
       registry['storage'] = {
         's3' => {
           'accesskey' => 'xxx',
           'secretkey' => 'xxx',
           'bucket' => 'registry',
           'regionendpoint' => 'https://gitlab-storage.xxx.org:9000',
           'region' => 'us-east-1'
         }
       }
```

**Comment by deekoder** [comment]
Will reopen this if we do this. For now I am closing this issue.

**Comment by iahmad-khan** [comment]
hi

i tried this configuration does not work for minio. is there something missing?

**Comment by krishnasrinivas** [comment]
@iahmad-khan we are not familiar with how gitlab uses minio. Can you check if this works for you? https://github.com/sameersbn/docker-gitlab/blob/master/docs/s3_compatible_storage.md

What errors are you getting?
Did you check with Gitlab folks on how they integrate with minio?

The instructions posted in this issue description might be outdated. It was provided by one of our community members.

Quick google search gave this blog post https://about.gitlab.com/2016/08/04/moving-to-gitlab-yes-its-worth-it/ can you see if it helps.

**Comment by iahmad-khan** [comment]
Hi,

I am using minio for gitlab backups , atifacts and lfs successfully. But the gitlab documentation for aws s3 for docker registry doesnt work for minio. they dont have any minio example.

I asked here just in case someone has used minio successfully for registry.
