### ISSUE TITLE
PHP SDK 

### ISSUE THREAD

**Issue by yebo29** [minio/cookbook#172]
Sorry for this extremely stupid question but I can't see it in the documentation. Using PHP, how do I:
1) Put any other object besides a text file, such as an image or tar file, etc
2) How would I delete an object?

Thanks and again sorry for the silly question and feel free to delete if it doesn't belong here.

**Comment by harshavardhana** [comment]
Here is the doc to get you started @yebo29  - https://docs.minio.io/docs/how-to-use-aws-sdk-for-php-with-minio-server

**Comment by yebo29** [comment]
Thank you @harshavardhana. That is the documentation I was reading however that shows how to put a text object, which I've done successfully. Now I need to try to upload images and others, which this documentation doesn't show. 
I'm currently going through the AWS docs at https://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/installation.html. Am I in the right place? Thanks once again for your help and stop me if this the wrong place.

**Comment by yebo29** [comment]
Is it something like this? 'Body'   => fopen($filename, 'r')

**Comment by yebo29** [comment]
It works! Figured it out. Guess I needed to just verbalize it. Thanks again. Closing.
