### ISSUE TITLE
Invalid links in Cloudberry doc

### ISSUE THREAD

**Issue by kannappanr** [minio/cookbook#200]
In the [Cloudberry Document](https://docs.minio.io/docs/how-to-use-cloudberry-drive-with-minio) , the link to Cloudberry Drive is invalid. 

Also, the document needs to be checked for proper English.

e.g. `Once CloudBerry Drive installed you can fine out its icon with configuration settings in your tray`

**Comment by harshavardhana** [comment]
FWIW we do not need this doc since Minio integration is native and CB has documented it properly on their end in detail.

**Comment by nitisht** [comment]
ok then we can remove this doc

**Comment by nitisht** [comment]
Here the CloudBerry documentation https://www.cloudberrylab.com/download/Installation-and-Configuration-Guide-CloudBerry-Backup-with-Minio.io.pdf
