### ISSUE TITLE
Translate new recipe 

### ISSUE THREAD

**Issue by nitisht** [minio/cookbook#207]
Translate the recipe https://github.com/minio/cookbook/blob/master/docs/multiple-minio-servers-with-nginx-inside-docker-container.md to `zh_CN`

**Comment by deekoder** [comment]
@dingjs  is on this.

**Comment by nitisht** [comment]
PR https://github.com/minio/cookbook/pull/208/

**Comment by nitisht** [comment]
fixed by #208
