### ISSUE TITLE
Prometheus: server returned HTTP status 403 Forbidden

### ISSUE THREAD

**Issue by KugelschreiberY** [minio/cookbook#217]
Hi there,

thanks for this nice helpers regarding minio. I am trying to pull metrics from minio via prometheus and have been following your instructions. Unfortunately I get the following error when I check the targets in the prometheus web ui: 

![image](https://user-images.githubusercontent.com/24484073/40238384-4fb4a77a-5ab3-11e8-8495-14e28d32d897.png)

Please note that I have implemented the prometheus and minio instance on an openshift cluster where `minio `is also the minio-pod's service name. 
When I try to access the metrics via the web interface i.e. minio/metrics I get the following error:

![image](https://user-images.githubusercontent.com/24484073/40238514-ad6a8092-5ab3-11e8-9085-2ba3b1d5846b.png)

Any idea how I can fix this problem? Thanks!

**Comment by nitisht** [comment]
@KugelschreiberY can you try `/minio/prometheus/metrics`

**Comment by KugelschreiberY** [comment]
@nitisht Thanks for the fast reply! I forgot to set the `metrics_path `in the prometheus.yml file.
Thanks a lot!

**Comment by andig** [comment]
I'm having the same problem deploying with coreos servicemonitor:

    apiVersion: v1
    kind: Service
    metadata:
      name: minio-metrics
      labels:
        app: minio
        scope: gsl-monitoring
    spec:
      ports:
      - name: metrics # expose metrics port
        port: 9000
        targetPort: service
        protocol: TCP
      selector:
        app: minio # target gitlab pods
    ---
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: minio-metrics-servicemonitor
      # Change this to the namespace the Prometheus instance is running in
      # namespace: default
      labels:
        app: minio
        release: prometheus
        scope: gsl-monitoring
    spec:
      selector:
        matchLabels:
          app: minio # target gitlab service
      endpoints:
      - port: metrics
        path: /minio/prometheus/metrics
        interval: 60s

Path is set in the servicemonitor endpoint?

**Comment by venkateswarlu009** [comment]
Hi 

I am getting below error in prometheus please help us


Endpoint | State | Labels | Last Scrape | Scrape Duration | Error
-- | -- | -- | -- | -- | --
http://54.162.1.205:8080/metrics | DOWN | instance="54.162.1.205:8080" job="jenkins" | 4.024s ago | 442.1ms | server returned HTTP status 403 Forbidden



My prometheus.yaml file like this

- job_name: 'jenkins'
     
    metrics_path: /metrics

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['54.162.1.205:8080']

**Comment by harshavardhana** [comment]
@venkateswarlu009 https://github.com/minio/minio/tree/master/docs/metrics/prometheus#3-configuring-prometheus
