### ISSUE TITLE
Clean up external pages with new content

### ISSUE THREAD

**Issue by deekoder** [minio/cookbook#22]
https://www.npmjs.com/package/minio 
it will be same for other places like python PyPi and all

Ported from docs.minio.io

**Comment by deekoder** [comment]
Next release.

**Comment by koolhead17** [comment]
add badges for python & other programming languages like nodejs.

**Comment by koolhead17** [comment]
@deekoder If we are not evaluating this anymore, we can close this.

**Comment by koolhead17** [comment]
@deekoder can we close this?

**Comment by koolhead17** [comment]
@GarimaKapoor @deekoder can this be closed?

**Comment by koolhead17** [comment]
minio-py has PyPi referenced in the footer. This can be closed.

**Comment by harshavardhana** [comment]
> minio-py has PyPi referenced in the footer. This can be closed.

losing..
