### ISSUE TITLE
letsencrypt for docker deployment

### ISSUE THREAD

**Issue by hadifarnoud** [minio/cookbook#224]
I used [this doc](https://docs.minio.io/docs/deploy-minio-on-docker-swarm.html) to install four docker nodes in one server. I followed [letsencrypt doc for minio](https://docs.minio.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio) to add SSL to my installation but did not find any directions for docker deployments. I am slightly confused about where should I add the certificates.

It might be super useful to update that doc and add steps for docker installs. not everyone is a docker-literate.

**Comment by nitisht** [comment]
Thanks for bringing this up @hadifarnoud we'll add the documentation

**Comment by nitisht** [comment]
@hadifarnoud closing this for now as we don't have cycles to do this.

The process for Docker containers/Swarm remains the same, i.e. 

- Create / Acquire certificates for each Minio service name (`minio1`, `minio2` .. etc in our docs)
- Add the private key and public certificate to the certs directory in `--certs-dir` (`~/.minio/certs` by default).
- In case of untrusted certs (e.g. self-signed) add trust for these certificates to Minio Server by placing these certificates under `--certs-dir/CAs` (`~/.minio/certs/CAs` by default).

You can use [Docker Secrets](https://docs.docker.com/engine/swarm/secrets/) to manage and mount sensitive data like certs and private keys to containers.

**Comment by hadifarnoud** [comment]
I would keep it in "future" milestone though
