### ISSUE TITLE
Invalid link for Hadoop download

### ISSUE THREAD

**Issue by hackintoshrao** [minio/cookbook#242]
The link for Hadoop download is invalid in the guide for [Apache Spark](https://github.com/minio/cookbook/blob/master/docs/apache-spark-with-minio.md). None of the [Download mirrors](http://mirrors.wuchna.com/apachemirror/hadoop/common/) currently host `Hadoop 2.8.2`.  Currently testing with `Hadoop 2.8.4`.

**Comment by nitisht** [comment]
Thanks for the pointer @hackintoshrao we'll fix the link. Meanwhile you can also use this http://archive.apache.org/dist/spark/spark-2.3.0/spark-2.3.0-bin-without-hadoop.tgz

**Comment by nitisht** [comment]
This link for Hadoop https://archive.apache.org/dist/hadoop/common/hadoop-2.8.2/hadoop-2.8.2.tar.gz

**Comment by deekoder** [comment]
@nitisht  is there going to be a PR fixing this?

**Comment by kannappanr** [comment]
PR #243 has been merged already. Closing this issue as fixed.
