### ISSUE TITLE
using javascript aws-sdk and AssumeRole for accessing MinIO 

### ISSUE THREAD

**Issue by thomaslange24** [minio/cookbook#257]
Hi, i need to use the javascript aws-sdk accessing MinIO with PutObject function. But instead of using direct credentials i would like to use the AssumeRole API like in https://github.com/minio/minio/blob/master/docs/sts/assume-role.md but using the javascript sdk. I tried it myself but ended confused about the different parameters the AssumeRole function needs and how to use the resulting credentials for accessing Minio. Can you give an example for that?

**Comment by thomaslange24** [comment]
Also with minio-js.

**Comment by thomaslange24** [comment]
I need some help. Because i can not figure out how to use the aws-sdk-js properly. It is a bit confusing. Because in the examples they do not set a specific endpoint and do not use user credentials. So how am i supposed to use this with MinIO? I guess sts.getFederationToken() is the right function to get temporary security credentials using already existing long-term user credentials. But how?

**Comment by harshavardhana** [comment]
It is very simple 

```js
// import entire SDK
var AWS = require('aws-sdk');
var sts = new AWS.STS({
    apiVersion: '2011-06-15',
    endpoint: 'http://localhost:9000',
    accessKeyId: 'foobar',
    secretAccessKey: 'foobar12345',
    s3ForcePathStyle: true,
    region: 'us-east-1',
});

var params = {
    DurationSeconds: 3600,
    ExternalId: "123ABC",
    Policy: '{"Version":"2012-10-17","Statement":[{"Sid":"Stmt1","Effect":"Allow","Action":"s3:*","Resource":"arn:aws:s3:::*"}]}',
    RoleArn: 'arn:xxx:xxx:xxx:xxxx',
    RoleSessionName: 'anything',
};

sts.assumeRole(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
});
```

```
$ mkdir aws
$ cd aws; npm install --save aws-sdk
$ node aws.js
{ ResponseMetadata: { RequestId: '15AFDF73A7053985' },
  Credentials:
   { AccessKeyId: 'X3UHJ5WM74VXLW8AV7FQ',
     SecretAccessKey: 'GbjhyDXON8CYb8XOq+tIpokd3CG2ywMg2OrMnJmI',
     SessionToken:
      'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJYM1VISjVXTTc0VlhMVzhBVjdGUSIsImV4cCI6MzYwMDAwMDAwMDAwMCwicG9saWN5IjoicmVhZG9ubHkiLCJzZXNzaW9uUG9saWN5IjoiZXlKV1pYSnphVzl1SWpvaU1qQXhNaTB4TUMweE55SXNJbE4wWVhSbGJXVnVkQ0k2VzNzaVUybGtJam9pVTNSdGRERWlMQ0pGWm1abFkzUWlPaUpCYkd4dmR5SXNJa0ZqZEdsdmJpSTZJbk16T2lvaUxDSlNaWE52ZFhKalpTSTZJbUZ5YmpwaGQzTTZjek02T2pvcUluMWRmUT09In0.Q5Kmj6M7XzgAzUHbYqAuzN4olpCWuByqjldeu7ApzxhmyMld20P6TFdW2OrlN0ohMcA8SM3K2us3yqjF3eEVlw',
     Expiration: 2019-07-10T00:01:23.000Z },
  AssumedRoleUser: { Arn: '' } }
```

**Comment by thomaslange24** [comment]
Thank you very much. So the Policy you provide as a parameter will intersect with the policy corresponding to the user credentials you are using to authenticate?

**Comment by harshavardhana** [comment]
Yes this is a wide example Policy is optional if you just want temporary keys.

**Comment by harshavardhana** [comment]
Best way to understand is test it @thomaslange24 and talk to us at https://slack.min.io - will close this issue for now.
