### ISSUE TITLE
It doesn't work for me reading minio's object from spark's RDD.

### ISSUE THREAD

**Issue by bellship** [minio/cookbook#262]
I followed cookbook/docs/apache-spark-with-minio.md. but It can't work.
![image](https://user-images.githubusercontent.com/37265872/60321120-64035080-996b-11e9-991e-f9eca8733473.png)

**Comment by harshavardhana** [comment]
This looks like you have some Java jars missing

**Comment by bellship** [comment]
I followed cookbook. could I check my missing jar file?
![image](https://user-images.githubusercontent.com/37265872/60322109-2c49d800-996e-11e9-9b28-f20466938cf7.png)

**Comment by bellship** [comment]
> This looks like you have some Java jars missing
I followed cookbook. could I check my missing jar file?
![image](https://user-images.githubusercontent.com/37265872/60325928-0f1a0700-9978-11e9-9218-fea737078dba.png)

**Comment by bellship** [comment]
It doesn't works for me.

**Comment by kannappanr** [comment]
@bellship Will take a look and see what jar files you might be missing.

**Comment by nitisht** [comment]
@bellship can you please paste your `$HADOOP_HOME/etc/hadoop/core-site.xml` file?

**Comment by nitisht** [comment]
Closing this due to no response, @bellship feel free to get back when you have the answers
