### ISSUE TITLE
When changing the URL for the S3 profile, CyberDuck automatically defaults the connection type to WebDav, fails.

### ISSUE THREAD

**Issue by jSadoski** [minio/cookbook#265]
As described, CyberDuck tries to intuit the type of connection incorrectly. I can no longer use the S3 (HTTP) profile other than to connect to the s3.amazonaws.com.

**Comment by harshavardhana** [comment]
@jSadoski is this our bug or Cyberduck ?

**Comment by jSadoski** [comment]
My mistake, this is Cyberduck!
