### ISSUE TITLE
minio deployed locally access it in spark shell, use domain name in fs.s3a.endpoint  error happens

### ISSUE THREAD

**Issue by Kaleidoscoper** [minio/cookbook#272]
I startup a minio server locally and try to access it in spark-shell . I just want to use the dns name instead of ip in the fs.s3a.endpoint and I got error while executing write files 
![image](https://user-images.githubusercontent.com/9138997/65009684-239ae980-d940-11e9-961d-dabc0d73be0d.png)

**Comment by kannappanr** [comment]
@Kaleidoscoper Can you access the minio endpoint when you try `http://minioservice:9010`.

Can you paste the output of `curl http://minioservice:9010` ?

**Comment by kannappanr** [comment]
@Kaleidoscoper Closing this issue as stale. Please feel free to reach out to us again when you have the information requested
