### ISSUE TITLE
AWS iOS SDK Cookbook for Swift 5 

### ISSUE THREAD

**Issue by ahikmatf** [minio/cookbook#276]
Related to #154 

Is there any update on the cookbook for Swift 5? Especially using `TransferUtility` but still using `AWSStaticCredentialsProvider`

Currently it works using `TransferManager` as stated in the cookbook, but having a problem with Server Side Encryption (KMS), it's uploaded but not encrypted, and sadly `TransferManager` deprecated

```swift
let uploadRequest = AWSS3TransferManagerUploadRequest()!
uploadRequest.serverSideEncryption = .awsKms
uploadRequest.ssekmsKeyId = kmsKey
```

**Comment by kannappanr** [comment]
@ahikmatf Can you please check on AWS ios SDK github repo? Because MinIO does not support `SSE-KMS` and you are using `AWS SDK` to talk to `AWS S3`, not sure where MinIO is involved here. 
Closing this issue now.

**Comment by ahikmatf** [comment]
#154 is related to this docs https://github.com/minio/cookbook/blob/master/docs/aws-sdk-for-iOS-with-minio.md @kannappanr , and MinIO used as our object storage

if SSE-KMS is not supported, then how can I know how to implement this for iOS, https://docs.min.io/docs/minio-kms-quickstart-guide.html ?

kinda stuck

**Comment by harshavardhana** [comment]
@ahikmatf please join our slack we can help you https;//slack.min.io
