### ISSUE TITLE
iOS using swift and AWSS3TransferUtility doesn't work.

### ISSUE THREAD

**Issue by gossmer** [minio/cookbook#286]
I wanted to change my code to use AWSS3TransferUtility because AWSS3TransferManager is deprecated. I tried the sample provided here and everything works fine with AWSS3TransferManager. Trying it with AWSS3TransferUtility and the request never completes. Can the sample be updated to work with AWSS3TransferUtility?

**Comment by harshavardhana** [comment]
> I wanted to change my code to use AWSS3TransferUtility because AWSS3TransferManager is deprecated. I tried the sample provided here and everything works fine with AWSS3TransferManager. Trying it with AWSS3TransferUtility and the request never completes. Can the sample be updated to work with AWSS3TransferUtility?

Unfortunately, AWSS3TransferUtility has been broken and been broken for a while, with no interest by AWS to fix it. So we can't do much though. 

So please use AWSS3TransferManager for now.

**Comment by kannappanr** [comment]
Closing this issue based on the above comment, please feel free to reach out to us at https://slack.min.io fur further such questions

**Comment by vasyares** [comment]
> I wanted to change my code to use AWSS3TransferUtility because AWSS3TransferManager is deprecated. I tried the sample provided here and everything works fine with AWSS3TransferManager. Trying it with AWSS3TransferUtility and the request never completes. Can the sample be updated to work with AWSS3TransferUtility?

Probably it can help you somehow because I was faced with infinity request too.
In my case it was required to add `continueWith` after `uploadData` call.
@gossmer please ping if you need help with it.

**Comment by gossmer** [comment]
@vasyares thanks. The continueWith is needed with AWSS3TransferManager. Even with AWSS3TransferUtility + continueWith, it doesn't return because there is a low level error. (with the header signature I think).

**Comment by gossmer** [comment]
> Unfortunately, AWSS3TransferUtility has been broken and been broken for a while, with no interest by AWS to fix it. So we can't do much though.
> 
> So please use AWSS3TransferManager for now.

Is there an issue created with AWS to fix it?
