### ISSUE TITLE
Erasue code QS guide image is a link

### ISSUE THREAD

**Issue by deekoder** [minio/cookbook#29]
https://thedoctor.herokuapp.com/docs/minio-erasure-code-quickstart-guide

it's an image. Should not be a link. It opens another site on click. Make it an image.

**Comment by koolhead17** [comment]
will be closed via https://github.com/minio/minio/pull/2263

**Comment by koolhead17** [comment]
also @deekoder this bug should have been assigned inside minio/minio

**Comment by deekoder** [comment]
We are keeping all docs bugs here
