### ISSUE TITLE
mc mirror quickstart and definitive guide

### ISSUE THREAD

**Issue by koolhead17** [minio/cookbook#56]
We can use `mc mirror` to take backup of one Minio setup to remote server. It needs to be documented.

**Comment by GarimaKapoor** [comment]
mc mirror simple set up is done. Advanced guide with bidirectional mirror is pending.

**Comment by koolhead17** [comment]
@GarimaKapoor Is this task still on going? How are we planning to work on this? please advice.

**Comment by koolhead17** [comment]
@GarimaKapoor @deekoder can this be closed?

**Comment by deekoder** [comment]
I think this can be closed.
