### ISSUE TITLE
provide example using aws-sdk for java

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/cookbook#96]
provide example using aws-sdk for java:
https://gist.github.com/krishnasrinivas/edc62873bcef5396493f31f8d582fc2c

**Comment by ankon** [comment]
Note that it would be nice to point out the various important pieces:
1. why/when to disable certificate checking, and the risk of doing so - the system property is global.
2. the signature version requirement
3. the path-style access requirement
4. why/when to disable chunked encoding

**Comment by krishnasrinivas** [comment]
actually dup of https://github.com/minio/cookbook/issues/92
