### ISSUE TITLE
Would like a cookbook for configuring minio in k8s with PersistentVolumes

### ISSUE THREAD

**Issue by jwalters-gpsw** [minio/cookbook#97]
I have been experimenting with Deis Workflow and want to use minio with PersistentVolumes in k8s. Would like to know how to configure my k8s configuration files to use PersistentVolumes/PersistentVolumeClaim.

**Comment by harshavardhana** [comment]
Thanks @jwalters-gpsw

**Comment by jwalters-gpsw** [comment]
I think I just need to know the following things:
Sample persistentvolume, sample persistentvolumeclaim and example pod creation yaml which uses the claim and shows the appropriate minio start options.

**Comment by harshavardhana** [comment]
ping @NitishT

**Comment by NitishT** [comment]
Working on a blog post to set up standalone Minio server on K8s. ETA 1 December.

**Comment by koolhead17** [comment]
This can be closed after https://github.com/minio/minio/pull/3684 gets merged.

**Comment by harshavardhana** [comment]
Fixed by https://github.com/minio/minio/pull/3684
